import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { AppProvider } from '@/providers/app-provider';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={cn(
          'absolute inset-0 font-sans antialiased',
          inter.className,
        )}
        suppressHydrationWarning
      >
        <main className="flex h-full">
          <AppProvider>{children}</AppProvider>
        </main>
        <Toaster
          closeButton
          visibleToasts={1}
          duration={10000}
          pauseWhenPageIsHidden
        />
      </body>
    </html>
  );
}
